name: Feature Request
about: Suggest a new feature for the ZTVS Go SDK
title: '[FEAT] '
labels: enhancement
assignees: ''

body:
  - type: textarea
    id: idea
    attributes:
      label: Describe your idea
      description: What would you like to see?
      placeholder: |
        I would love to have support for...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is this related to a problem?
      description: Explain the use case and context.
      placeholder: |
        Right now, it is hard to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: How should this work?
      placeholder: |
        The SDK should provide a...
    validations:
      required: true
