name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.26.x'

    - name: Install dependencies
      run: |
        go mod download
        cd examples/hello-world && go mod download

    - name: Run SDK tests
      run: go test -v ./...
      working-directory: .

    - name: Run Example tests
      run: go test -v ./...
      working-directory: examples/hello-world

    - name: Build Example
      run: go build -v ./...
      working-directory: examples/hello-world
